// userActions
export const SET_VALIDATION_ERRORS = "SET_VALIDATION_ERRORS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//  Category Actions
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const GET_CATEGORIES_ERR = "GET_CATEGORIES_ERR";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const SEARCH_CATEGORY = "SEARCH_CATEGORY";
export const CLEAR_CATEGORIES = "CLEAR_CATEGORIES";

// Product Actions
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_ERR = "GET_PRODUCTS_ERR";
export const UPLOAD_PRODUCT = "UPLOAD_PRODUCT";
export const UPLOAD_PRODUCT_ERR = "UPLOAD_PRODUCT_ERR";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const GET_SINGLE_PRODUCT = "GET_SINGLE_PRODUCT";
export const GET_SINGLE_PRODUCT_ERR = "GET_SINGLE_PRODUCT_ERR";
export const CLEAR_SINGLE_PRODUCT = "CLEAR_SINGLE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_ERR = "UPDATE_PRODUCT_ERR";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const FILE_UPLOAD_LOADER = "FILE_UPLOAD_LOADER";

// App actions
export const SET_LOADER = "SET_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";
export const TOGGLE_SNACKBAR = "TOGGLE_SNACKBAR";